### ISSUE TITLE
svg compatibility problems

### ISSUE THREAD

**Issue by abductedPlatypus** [SiegeEngineers/SiegeEngineers-CD#1]
I can't get this to display properly in Illustrator CS5 (even with fonts installed)
![siegeengineersaifail](https://user-images.githubusercontent.com/27150757/51840355-1fb44b80-230c-11e9-894b-68bed3729b2a.png)
There is also a scaling issue in chrome for the Github preview.

**Comment by HSZemi** [comment]
I am not too surprised that Illustrator does not understand what Inkscape tries to tell it.
By "scaling issue", do you mean that the S is too far to the left?

**Comment by abductedPlatypus** [comment]
You don't have any feature/versioning options when exporting?

Upon inspection I see that is probably not scaling but a position problem; the S touch almost the left bricks. So it could be text alignment. (ah you edited that later, I shouldn't just read the mail, so yes)
![image](https://user-images.githubusercontent.com/27150757/51870660-8b220b80-2354-11e9-8f49-d7a71c7f0fcd.png)

It's one of the few things that does work in Illustrator though.

**Comment by HSZemi** [comment]
Yes. Unfortunately, Inkscape has always been kind of particular in how it interprets/stores svg files, especially when it comes to text, blur, gradients, and filters :disappointed:

**Comment by Dico200** [comment]
Maybe render a very large version of it and use the resulting image file?

**Comment by HSZemi** [comment]
Commit 017782875f5f229491e5307834315e232adab068 might be an improvement

**Comment by abductedPlatypus** [comment]
Yes, that fixed it. Thanks!
